### ISSUE TITLE
Transfer unweb username?

### ISSUE THREAD

**Issue by mattfysh** [unweb/unweb.me-Mockup#1]
Hi @yconst @d-mo @mgogoulos :wave:

I'm building a new dashboard app leveraging AI and web scrapers to implement a type of "virtual personal assistant" tool. I'm calling it **"unweb"** and I've registered unweb.io and getunwebbed.com

I'm wondering if you were still using this github org name, and if not, would you be open to transferring the github username?

Many thanks, Matt.

**Comment by mattfysh** [comment]
Hi @yconst @d-mo @mgogoulos ... are you the best guys to contact or is there someone else who might be able to help out? thanks!

**Comment by d-mo** [comment]
@mattfysh Please choose another username.
